services:

  web-db:
    build: ./database
    container_name: web-db
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env

  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - web-db

volumes:
  db-data:
    name: db-data
